language: node_js
node_js:
  - '5.2'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bower install -f
  - gulp build

script:
- node_modules/.bin/karma start tests/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
